[package]
name = "greetings"
version = "0.1.0"
authors = ["唐盛 <tangsheng02@meituan.com>"]

[lib]
crate-type = ["dylib"]

[target.'cfg(target_os="android")'.dependencies]
jni = {version = "0.5", default-features = false}

[dependencies]
