[target.aarch64-linux-android]
ar = "src/greetings/NDK/arm64/bin/aarch64-linux-android-ar"
linker = "src/greetings/NDK/arm64/bin/aarch64-linux-android-clang"

[target.armv7-linux-androideabi]
ar = "src/greetings/NDK/arm/bin/arm-linux-androideabi-ar"
linker = "src/greetings/NDK/arm/bin/arm-linux-androideabi-clang"

[target.i686-linux-android]
ar = "src/greetings/NDK/x86/bin/i686-linux-android-ar"
linker = "src/greetings/NDK/x86/bin/i686-linux-android-clang"
